jobs:
- job: Lint
  variables:
  - template: ../variables/variables-common.yml
  # platform specific variables, links to
  - template: ../variables/variables.yml
  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged --env container=docker
  steps:
    - template: ../templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        echo "Running make target 'lint'"
        make V=0 lint
        echo "Building documentation"
        make -C doc/ html
      displayName: Lint sources and documentation
    - template: ../templates/save-test-artifacts.yml
      parameters:
        logsPath: doc/_build/html
        logsArtifact: docs-$(System.JobIdentifier)-$(Build.BuildId)-$(System.StageAttempt)-$(System.PhaseAttempt)-$(System.JobPositionInPhase)
