jobs:
- job: Tox
  variables:
  - template: ../variables/variables-common.yml
  # platform specific variables, links to
  - template: ../variables/variables.yml

  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged --env container=docker
  steps:
    - template: ../templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ variables.AZURE_PYTHON_VERSION }}
        architecture: x64
    - template: ../templates/${{ variables.PREPARE_TOX_TEMPLATE }}
    - script: |
        set -e
        echo "Running tox"
        export LANG=en_US.utf8
        export LC_CTYPE=en_US.utf8
        locale
        $(TOX_COMMAND) -e py3,pypi,pylint3
      displayName: Tox
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '.tox/**/junit-*.xml'
        testRunTitle: 'Tox results'
      condition: succeededOrFailed()
