jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-master-f27
          version: 1.0.1
        timeout: 1800

  fedora-27/simple_replication:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_simple_replication.py
        template: *ci-master-f27
        timeout: 3600

  fedora-27/caless:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_caless.py::TestServerReplicaCALessToCAFull
        template: *ci-master-f27
        timeout: 3600

  fedora-27/external_ca:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_external_ca.py::TestExternalCA
        template: *ci-master-f27
        timeout: 3600
