FROM docker_tests_image
ENV container=docker LANG=en_US.utf8 LANGUAGE=en_US.utf8 LC_ALL=en_US.utf8

COPY dist /root
RUN \
    apt-get update \
    && apt-get install \
        -o 'Debug::pkgProblemResolver=yes' \
        -o 'Debug::pkgRemoveDepends=yes' \
        -o 'Debug::pkgMarkInstall=yes' \
        -y \
        /root/rpms/*.rpm openssh \
        gssproxy-nfs-server nfs-server \
    && apt-get clean \
    && find /var/lib/apt/lists/ -type f -exec rm "{}" \; \
    && rm -rf /var/cache/apt/*.bin \
    && mkdir -p /rpms/x86_64/RPMS.local_rpms \
    && mkdir -p /rpms/x86_64/RPMS.local_debug_rpms \
    && mv /root/rpms/*.rpm /rpms/x86_64/RPMS.local_rpms/ \
    && mv /root/rpms_debuginfo/*.rpm /rpms/x86_64/RPMS.local_debug_rpms/ \
    && apt-repo add 'rpm-dir file:/rpms x86_64 local_rpms' \
    && rm -rf /root/rpms /root/srpms /root/rpms_debuginfo \
    && sed -i 's/.*PermitRootLogin .*/#&/g' /etc/openssh/sshd_config \
    && echo 'PermitRootLogin yes' >> /etc/openssh/sshd_config \
    && systemctl enable sshd
VOLUME ["/freeipa"]
ENTRYPOINT [ "/sbin/init" ]
