trigger:
- master

stages:
- stage: build_and_test
  displayName: Build and Test FreeIPA

  jobs:
  - template: jobs/build.yml
  - template: jobs/lint.yml
  - template: jobs/tox.yml
  - template: jobs/webui_unittests.yml
  - template: jobs/base_xmlrpc.yml
  - template: jobs/gating.yml
