trigger:
- master

variables:
- template: templates/variables-common.yml
# platform specific variables, links to
- template: templates/variables.yml

jobs:
- job: Build
  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        git update-ref refs/heads/$(System.PullRequest.TargetBranch) origin/$(System.PullRequest.TargetBranch)
        make V=0 "GIT_BRANCH=$(System.PullRequest.TargetBranch)" fastlint
      displayName: Quick code style check
      condition: eq(variables['Build.Reason'], 'PullRequest')
    - template: templates/${{ variables.BUILD_TEMPLATE }}
    - script: |
        set -e
        mkdir container
        cp -pr dist container/
        cp ipatests/azure/$(DOCKER_DOCKERFILE) container/Dockerfile
        cd container
        docker build -t freeipa-azure-builder .
        docker save freeipa-azure-builder | gzip > '$(builddir)/freeipa-azure-builder-container.tar.gz'
      displayName: Create container image for test
    - template: templates/publish-build.yml

- job: Lint
  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        echo "Running make target 'lint'"
        make V=0 lint
      displayName: Lint sources

- job: Tox
  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
        architecture: x64
    - template: templates/${{ variables.PREPARE_TOX_TEMPLATE }}
    - script: |
        set -e
        echo "Running tox"
        export LANG=en_US.utf8
        export LC_CTYPE=en_US.utf8
        locale
        tox -e py37,pypi,pylint3
      displayName: Tox
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '.tox/**/junit-*.xml'
        testRunTitle: 'Tox results'
      condition: succeededOrFailed()

- job: WebUI_Unit_Tests
  pool:
    vmImage: $(VM_IMAGE)
  container:
    image: $(DOCKER_BUILD_IMAGE)
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/${{ variables.PREPARE_BUILD_TEMPLATE }}
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
        architecture: x64
    - template: templates/${{ variables.PREPARE_WEBUI_TEMPLATE }}
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        echo "Running WebUI unit tests"
        cd $(builddir)/install/ui/js/libs && make
        cd $(builddir)/install/ui && npm install
        cd $(builddir)/install/ui && node_modules/grunt/bin/grunt --verbose test
      displayName: WebUI Unit Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'install/ui/_build/test-reports/TEST-*.xml'
        testRunTitle: 'Web UI unit test results'
      condition: succeededOrFailed()

- job: BASE_XMLRPC
  pool:
    vmImage: $(VM_IMAGE)
  dependsOn: Build
  condition: succeeded()
  strategy:
    parallel: 3
  steps:
  - template: templates/test-jobs.yml
    parameters:
      testsToRun:
      - test_cmdline
      - test_install
      - test_ipaclient
      - test_ipalib
      - test_ipaplatform
      - test_ipapython
      - test_ipaserver
      - test_ipatests_plugins
      - test_xmlrpc
      testsToIgnore:
      - test_integration
      - test_webui
      - test_ipapython/test_keyring.py
      testsToDedicate:
      - test_xmlrpc/test_dns_plugin.py
      taskToRun: run-tests

- job: GATING
  pool:
    vmImage: $(VM_IMAGE)
  dependsOn: Build
  condition: succeeded()
  strategy:
    matrix:
      installation_TestInstallMaster:
        testsToRun: test_integration/test_installation.py::TestInstallMaster
      kerberos_flags:
        testsToRun: test_integration/test_kerberos_flags.py
        testsClients: 1
      dnssec_TestInstallDNSSECFirst:
        testsToRun: test_integration/test_dnssec.py::TestInstallDNSSECFirst
        testsReplicas: 1
      simple_replication:
        testsToRun: test_integration/test_simple_replication.py
        testsReplicas: 1
      caless_TestServerReplicaCALessToCAFull:
        testsToRun: test_integration/test_caless.py::TestServerReplicaCALessToCAFull
        testsReplicas: 1
      external_ca_TestExternalCA:
        testsToRun: test_integration/test_external_ca.py::TestExternalCA
        testsReplicas: 1
        testsClients: 1
      external_ca_TestSelfExternalSelf:
        testsToRun: test_integration/test_external_ca.py::TestSelfExternalSelf
      external_ca_TestExternalCAInstall:
        testsToRun: test_integration/test_external_ca.py::TestExternalCAInstall
      # requires nothing, don't install anything
      topologies_and_testconfig:
        testsToRun: test_integration/test_topologies.py test_integration/test_testconfig.py
      #
      commands:
        testsToRun: test_integration/test_commands.py
      sudo:
        testsToRun: test_integration/test_sudo.py
        testsClients: 1
      forced_client_reenrollment:
        testsToRun: test_integration/test_forced_client_reenrollment.py
        testsReplicas: 1
        testsClients: 1
      service_permissions:
        testsToRun: test_integration/test_service_permissions.py
      netgroup:
        testsToRun: test_integration/test_netgroup.py
      replica_promotion_TestSubCAkeyReplication:
        testsToRun: test_integration/test_replica_promotion.py::TestSubCAkeyReplication
        testsReplicas: 1
  timeoutInMinutes: 90

  steps:
  - script: |
      set -e
      echo "##vso[task.setvariable variable=ntestsClients]${TESTSCLIENTS:-0}"
      echo "##vso[task.setvariable variable=ntestsReplicas]${TESTSREPLICAS:-0}"
    displayName: Generate variables

  - template: templates/test-jobs.yml
    parameters:
      taskToRun: run-integration-tests
      testsToRun: "$(testsToRun)"
      topology:
        clients: "$(ntestsClients)"
        replicas: "$(ntestsReplicas)"

- job: GATING_
  pool:
    vmImage: $(VM_IMAGE)
  dependsOn: Build
  condition: succeeded()
  strategy:
    matrix:
      installation_TestInstallMaster:
        testsToRun: test_integration/test_installation.py::TestInstallMaster
  timeoutInMinutes: 90

  steps:
  - script: |
      set -e
      echo "##vso[task.setvariable variable=ntestsClients]${TESTSCLIENTS:-0}"
      echo "##vso[task.setvariable variable=ntestsReplicas]${TESTSREPLICAS:-0}"
    displayName: Generate variables

  - template: templates/test-jobs.yml
    parameters:
      taskToRun: run-integration-tests
      testsToRun: "$(testsToRun)"
      topology:
        clients: "$(ntestsClients)"
        replicas: "$(ntestsReplicas)"
