variables:
  CI_RUNNER_LOGS_DIR: logs
  localsdir: $(Build.Repository.LocalPath)
  builddir: /__w/1/s

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'
  container:
    image: stanislavlevin/freeipa-build-altlinux:sisyphus
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/prepare-build.yml
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        git update-ref refs/heads/$(System.PullRequest.TargetBranch) origin/$(System.PullRequest.TargetBranch)
        make V=0 "GIT_BRANCH=$(System.PullRequest.TargetBranch)" fastlint
      displayName: Quick code style check
      condition: eq(variables['Build.Reason'], 'PullRequest')
    - script: |
        set -e
        echo "Build rpms"
        gear-rpm -ba -v \
            --define '_topdir $(builddir)/rpmbuild' \
            --without 'lint' \
            --without 'fasttest' \
            --without 'fastlint'
        mkdir -p $(builddir)/dist/{,s}rpms
        cp -v $(builddir)/rpmbuild/SRPMS/freeipa-*.src.rpm $(builddir)/dist/srpms/
        find $(builddir)/rpmbuild/RPMS/ -type f \( -not -name "*-debuginfo-*" \
            -a -name '*.rpm' \) -exec cp {} $(builddir)/dist/rpms/ \;
      displayName: Build packages
    - script: |
        set -e
        mkdir container
        cp -pr dist container/
        cp ipatests/azure/Dockerfile-altlinux.build-container container/Dockerfile
        cd container
        docker build -t freeipa-fedora-builder .
        docker save freeipa-fedora-builder | gzip > '$(builddir)/freeipa-fedora-builder-container.tar.gz'
      displayName: Create container image for test
    - template: templates/publish-build.yml

- job: Lint
  pool:
    vmImage: 'Ubuntu-16.04'
  container:
    image: stanislavlevin/freeipa-build-altlinux:sisyphus
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/prepare-build.yml
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        echo "Running make target 'lint'"
        make V=0 lint
      displayName: Lint sources

- job: Tox
  pool:
    vmImage: 'Ubuntu-16.04'
  container:
    image: stanislavlevin/freeipa-build-altlinux:sisyphus
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/prepare-build.yml
    - script: |
        set -e
        sudo apt-get install -y nss-utils python3-module-pip
        python3 -m pip install --user --upgrade pip setuptools pycodestyle
      displayName: 'Install prerequisites'
    - script: |
        set -e
        echo "Running tox"
        export LANG=en_US.utf8
        export LC_CTYPE=en_US.utf8
        locale
        tox.py3 -e py37,pypi,pylint3
      displayName: Tox
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '.tox/**/junit-*.xml'
        testRunTitle: 'Tox results'
      condition: succeededOrFailed()

- job: WebUI_Unit_Tests
  pool:
    vmImage: 'Ubuntu-16.04'
  container:
    image: stanislavlevin/freeipa-build-altlinux:sisyphus
    options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged
  steps:
    - template: templates/prepare-build.yml
    - script: |
        set -e
        sudo apt-get -y install npm fontconfig
      displayName: 'Install prerequisites'
    - script: |
        set -e
        echo "Running autoconf generator"
        ./autogen.sh
      displayName: Configure the project
    - script: |
        set -e
        echo "Running WebUI unit tests"
        cd $(builddir)/install/ui/js/libs && make
        cd $(builddir)/install/ui && npm install
        cd $(builddir)/install/ui && node_modules/grunt/bin/grunt --verbose test
      displayName: WebUI Unit Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'install/ui/_build/test-reports/TEST-*.xml'
        testRunTitle: 'Web UI unit test results'
      condition: succeededOrFailed()

      # - template: templates/test-jobs.yml
      #   parameters:
      #     jobs:
      #     - job: installation_TestInstallMaster
      #       testsToRun:
      #       - test_integration/test_installation.py::TestInstallMaster
      #       - test_test.py
      #     - job: kerberos_flags
      #       testsToRun:
      #       - test_integration/test_kerberos_flags.py
      #       topology:
      #         clients: 1
      #     taskToRun: run-integration-tests


- job: GATING
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: Build
  condition: succeeded()
  strategy:
    matrix:
      nfs:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_1:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_2:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_3:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_4:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_5:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_6:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_7:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_8:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_9:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_10:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_11:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_12:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
      nfs_13:
        testsToRun: test_integration/test_nfs.py
        testsClients: 3
  timeoutInMinutes: 90

  steps:
  - script: |
      set -e
      echo "##vso[task.setvariable variable=testsClients]${TESTSCLIENTS:-0}"
      echo "##vso[task.setvariable variable=testsReplicas]${TESTSREPLICAS:-0}"
    displayName: Generate variables

  - template: templates/test-jobs.yml
    parameters:
      taskToRun: run-integration-tests
      testsToRun: "$(testsToRun)"
      topology:
        clients: "$(testsClients)"
        replicas: "$(testsReplicas)"
